"""
Whitepaper Generator - Creates LaTeX PDFs from LLM notes

SPOF #5 Fix: Falls back to Markdown if LaTeX compilation fails
"""
import subprocess
from pathlib import Path
from datetime import datetime


class WhitepaperGenerator:
    def __init__(self, output_dir="docs/whitepapers", prefer_markdown=False):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.prefer_markdown = prefer_markdown

    def _latex_to_markdown(self, latex_text: str) -> str:
        """
        Convert basic LaTeX to Markdown.

        Simple conversion for common patterns.
        """
        md = latex_text

        # Remove LaTeX commands
        md = md.replace("\\begin{abstract}", "## Abstract\n")
        md = md.replace("\\end{abstract}", "")
        md = md.replace("\\section{", "\n## ")
        md = md.replace("\\subsection{", "\n### ")
        md = md.replace("}", "")
        md = md.replace("\\textit{", "*")
        md = md.replace("\\textbf{", "**")

        # Remove extra backslashes
        md = md.replace("\\\\", "\n")
        md = md.replace("\\", "")

        return md

    def _generate_markdown(self, llm_agent, data: dict, filename: str) -> str:
        """
        Generate Markdown report as fallback.

        Args:
            llm_agent: LLM agent (may be in offline mode)
            data: Simulation data
            filename: Output filename

        Returns:
            Path to generated Markdown file
        """
        # Generate sections using LLM (or offline fallback)
        abstract = llm_agent.generate_whitepaper_section("abstract", data)
        results = llm_agent.generate_whitepaper_section("results", data)
        discussion = llm_agent.generate_whitepaper_section("discussion", data)

        # Convert LaTeX to Markdown if needed
        abstract_md = self._latex_to_markdown(abstract)
        results_md = self._latex_to_markdown(results)
        discussion_md = self._latex_to_markdown(discussion)

        # Assemble Markdown document
        markdown = f"""# Hierarchical Information Dynamics: Computational Exploration

**Generated by:** iVHL Framework + Qwen2.5-2B AI Assistant
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

{abstract_md}

---

## Introduction

This report presents results from a computational simulation exploring
information flow in hierarchical tensor networks. This is a **MATHEMATICAL
study**, not a physical theory.

{results_md}

{discussion_md}

---

## Conclusion

This simulation demonstrated computational patterns in tensor network
compression. All results represent abstract mathematical structures.

**Disclaimer**: This work explores mathematical models only.
No claims are made about physical reality, dark matter, cosmology, or
quantum gravity.

---

## Simulation Parameters

- **Layers:** {data.get('num_layers', 'N/A')}
- **Base Dimension:** {data.get('base_dim', 'N/A')}
- **Bond Dimension:** {data.get('bond_dim', 'N/A')}
- **Timesteps:** {data.get('timesteps', 'N/A')}
- **Device:** {data.get('device', 'N/A')}

---

*Report generated by iVHL Framework*
"""

        # Write Markdown
        md_path = self.output_dir / f"{filename}.md"
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(markdown)

        print(f"✅ Markdown report generated: {md_path}")
        return str(md_path)

    def generate(self, llm_agent, data: dict, filename="hierarchical_dynamics"):
        """
        Generate whitepaper (PDF preferred, Markdown fallback).

        Args:
            llm_agent: LLM agent for content generation
            data: Simulation data
            filename: Output filename (without extension)

        Returns:
            Path to generated file
        """
        # If markdown preferred or LaTeX unavailable, skip PDF
        if self.prefer_markdown or not self._check_pdflatex():
            print("📝 Generating Markdown report (LaTeX unavailable)")
            return self._generate_markdown(llm_agent, data, filename)

        # Try PDF generation
        try:
            # Generate sections using LLM
            abstract = llm_agent.generate_whitepaper_section("abstract", data)
            results = llm_agent.generate_whitepaper_section("results", data)
            discussion = llm_agent.generate_whitepaper_section("discussion", data)

            # Assemble LaTeX document
            latex = f"""\\documentclass{{article}}
\\usepackage{{amsmath}}
\\usepackage{{graphicx}}
\\usepackage{{hyperref}}

\\title{{Hierarchical Information Dynamics: Computational Exploration}}
\\author{{iVHL Framework + Qwen2.5-2B AI Assistant}}
\\date{{\\today}}

\\begin{{document}}
\\maketitle

{abstract}

\\section{{Introduction}}
This whitepaper presents results from a computational simulation exploring
information flow in hierarchical tensor networks. This is a MATHEMATICAL
study, not a physical theory.

{results}

{discussion}

\\section{{Conclusion}}
This simulation demonstrated computational patterns in tensor network
compression. All results represent abstract mathematical structures.

\\textbf{{Disclaimer}}: This work explores mathematical models only.
No claims are made about physical reality, dark matter, cosmology, or
quantum gravity.

\\end{{document}}
"""

            # Write LaTeX
            tex_path = self.output_dir / f"{filename}.tex"
            with open(tex_path, 'w', encoding='utf-8') as f:
                f.write(latex)

            # Compile PDF
            result = subprocess.run(
                ['pdflatex', '-output-directory', str(self.output_dir), str(tex_path)],
                check=True,
                capture_output=True,
                timeout=60
            )

            pdf_path = self.output_dir / f"{filename}.pdf"
            if pdf_path.exists():
                print(f"✅ Whitepaper PDF generated: {pdf_path}")
                return str(pdf_path)
            else:
                raise FileNotFoundError("PDF not created")

        except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError) as e:
            print(f"⚠️  PDF generation failed: {e}")
            print("📝 Falling back to Markdown report...")

            # Fallback to Markdown
            return self._generate_markdown(llm_agent, data, filename)

    def _check_pdflatex(self) -> bool:
        """Check if pdflatex is available."""
        try:
            subprocess.run(
                ['pdflatex', '--version'],
                capture_output=True,
                timeout=5
            )
            return True
        except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
            return False
